import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.cake}>
          <Image
            src="/assets/images/cake_cutout.png"
            alt="A sexy cake picture"
            layout="fill"
          />
        </div>
        <div className="text-center bg-white p-5 relative">
          <h1 className="m-0 text-7xl font-bold mb-4">The Cake Lab 3.0</h1>
          <p>Coming soon.</p>
        </div>
      </main>
    </div>
  );
};

export default Home;
